name: naveye
description: "NavEye - AI-based Assistance System for Blind People"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Camera
  camera: ^0.10.5+9

  # AI / Object Detection
  tflite_flutter: ^0.10.4
  image: ^4.1.7

  # Text to Speech
  flutter_tts: ^4.0.2

  # Local Database
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Preferences
  shared_preferences: ^2.2.3

  # Permissions
  permission_handler: ^11.3.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/
    - assets/images/